import 'package:isar/isar.dart';

part 'recently_played.g.dart'; // Generated by Isar

@Collection()
class RecentlyPlayed {
  Id? id; // unique identifer for each liked song

  late String songName; // name of the song
  late String songArtists; // song artists name
  late String songImageUrl; // link of the song's image

  late DateTime playedAt; // Timestamp of when the song was played
}
