import 'package:isar/isar.dart';

part 'recently_played.g.dart'; // Generated by Isar

@Collection()
class RecentlyPlayed {
  Id id = Isar.autoIncrement; // Unique identifier for each record

  late int songId;        // Reference to the Song ID
  late DateTime playedAt; // Timestamp of when the song was played
}
