import 'package:isar/isar.dart';

part 'song.g.dart'; // Generated by Isar

@Collection()
class SongModel {
  Id id = Isar.autoIncrement; // Unique identifier for each song

  late String imageUrl;   // URL of the song's image/cover
  late String songName;   // Name of the song
  late String artists;    // Artists' names as a single string
}